#knif1e4j:
#  enable: true
#  setting:
basic:
#    enable: true
#    # Basic认证用户名
#    username: admin
#    # Basic认证密码
#    password: 000
## Swagger配置
#swagger:
#  # 是否开启swagger
#  enabled: true
#  # 请求前缀
#  pathMapping: /dev-api
#Swagger配置
knife4j:
  enable: true
  documents:
    -
      group: 系统文档
      name: 系统文档
      locations: classpath:markdown/*
  setting:
    language: zh-CN
    enableDocumentManage: true
    enableSwaggerModels: true
    swaggerModelName: 实体类列表
    enableVersion: true
    enableReloadCacheParameter: false
    enableAfterScript: true
    enableFilterMultipartApiMethodType: POST
    enableFilterMultipartApis: false
    enableRequestCache: true
    enableHost: false
    enableHostText: 192.168.0.193:8000
    enableHomeCustom: true
    homeCustomLocation: classpath:markdown/*.md
    enableSearch: false
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Lucky-Pet医院商城
    enableDynamicParameter: true
    enableDebug: true
    enableOpenApi: true
    enableGroup: true
  cors: false
  production: false
  basic:
    enable: true
    username: admin
    password: 123123


springfox:
  documentation:
    open-api:
      enabled: true
